import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const artifactPath = resolve(
  __dirname,
  "../artifacts/contracts/PropertyShares.sol/PropertyShares.json"
);
const outputPath = resolve(__dirname, "../../../apps/web/src/lib/propertySharesAbi.ts");
const artifact = JSON.parse(readFileSync(artifactPath, "utf8")) as { abi: unknown };

const content =
  "// This file is generated by pnpm contracts:compile. Do not edit manually.\n" +
  "export const propertySharesAbi = " +
  JSON.stringify(artifact.abi, null, 2) +
  " as const;\n";

writeFileSync(outputPath, content);
console.log("Synchronized PropertyShares ABI to apps/web.");
